### ISSUE TITLE
Archive a Binder/Export

### ISSUE THREAD

**Issue by hestonpaes** [gitcac/eMeetings#194]
After an eBinder has been marked as inactive, the user(committee coordinators) has the ability to archive the binder.  This would take an full export(see export binder) of the binder as of that moment with all content except ministry private notes.  This is also called the "official binder"

The user has the option to save this in the most appropriate location and then have the ability to remove the eBinder from the site.

It was discussed if ministries should be able to export their own version(official binder + their notes) but hoping we can push back, since ministries will probably do their own records management.  Currently binders are currently shredded after the meeting and only the official binder is kept as a record.

**Comment by hfazal** [comment]
Completed by @SIlver-- in 79a8652
